/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crud;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


/**
 *
 * @author casa
 */
public class main extends javax.swing.JFrame {
    
    PreparedStatement ps;

    ResultSet rs;
    
    public main() {
        String[] genero = {"M", "F"};
        initComponents();
        this.gender.addItem(genero[0]);
        this.gender.addItem(genero[1]);
        this.setLocationRelativeTo(null);
    }
    
    public void cleanInputs(){
        this.ccTxt.setText("");
        this.lastTxt.setText("");
        this.nameTxt.setText("");
        this.ageTxt.setText("");
        this.phoneTxt.setText("");
        this.mobileTxt.setText("");
        this.gender.setSelectedIndex(0);
        this.ccTxt.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ccTxt = new javax.swing.JTextField();
        lastTxt = new javax.swing.JTextField();
        nameTxt = new javax.swing.JTextField();
        ageTxt = new javax.swing.JTextField();
        phoneTxt = new javax.swing.JTextField();
        mobileTxt = new javax.swing.JTextField();
        gender = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        eliminar = new javax.swing.JButton();
        buscar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        ingresar = new javax.swing.JButton();
        borrarLbl = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(ccTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 150, 30));
        getContentPane().add(lastTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 150, 30));
        getContentPane().add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 150, 30));
        getContentPane().add(ageTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 150, 30));
        getContentPane().add(phoneTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 150, 30));

        mobileTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileTxtActionPerformed(evt);
            }
        });
        getContentPane().add(mobileTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 150, 30));

        getContentPane().add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 150, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cedula");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 150, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apellidos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 150, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 150, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sexo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 150, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Edad");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 150, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Telefono");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 150, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Celular");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 150, 30));

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 150, 34));

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        getContentPane().add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 150, 34));

        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        getContentPane().add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 150, 34));

        ingresar.setText("Ingresar");
        ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarActionPerformed(evt);
            }
        });
        getContentPane().add(ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 150, 34));

        borrarLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        borrarLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/notes.png"))); // NOI18N
        borrarLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrarLblMouseClicked(evt);
            }
        });
        getContentPane().add(borrarLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 40, 40));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Tienda ABC");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 270, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/blackboard.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void mobileTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileTxtActionPerformed

    private void borrarLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrarLblMouseClicked
        this.cleanInputs();
    }//GEN-LAST:event_borrarLblMouseClicked

    private void ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarActionPerformed
        com.mysql.jdbc.Connection con = null;
        try {
            con = conect.getConection();
            ps = con.prepareStatement("INSERT INTO empleado(CEDULA,NOMBRE,APELLIDO,EDAD,SEXO,TELEFONO,CELULAR) VALUES(?,?,?,?,?,?,?)");
            ps.setString(1, this.ccTxt.getText());
            ps.setString(2, this.nameTxt.getText());
            ps.setString(3, this.lastTxt.getText());
            ps.setString(4, this.ageTxt.getText());
            ps.setString(5, this.gender.getSelectedItem().toString());
            ps.setString(6, this.phoneTxt.getText());
            ps.setString(7, this.mobileTxt.getText());
            int res = ps.executeUpdate();
            if (res > 0) {
                JOptionPane.showMessageDialog(null, "Agregado con exito");
            }else{
                JOptionPane.showMessageDialog(null, "Proceso fallido");
            }
            con.close();
        } catch (Exception e) {
            System.out.println("Error en la insercion "+e);
        }
        this.cleanInputs();
    }//GEN-LAST:event_ingresarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        com.mysql.jdbc.Connection con = null;
        try {
            con = conect.getConection();
            
            ps = con.prepareStatement("SELECT * FROM empleado WHERE CEDULA = ?");
            
            ps.setString(1, this.ccTxt.getText());
            rs = ps.executeQuery();
            
            if (rs.next()) {
                this.lastTxt.setText(rs.getString("APELLIDO"));
                this.nameTxt.setText(rs.getString("NOMBRE"));
                this.ageTxt.setText(rs.getString("EDAD"));
                this.phoneTxt.setText(rs.getString("TELEFONO"));
                this.mobileTxt.setText(rs.getString("CELULAR"));
                this.gender.setSelectedItem(rs.getString("SEXO"));
            } else {
                JOptionPane.showMessageDialog(null, "No se encontraron los datos");
            }
            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_buscarActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        com.mysql.jdbc.Connection con = null;
        try {
            con = conect.getConection();

            ps = con.prepareStatement("UPDATE empleado SET CEDULA = ?, NOMBRE = ?, APELLIDO = ?, EDAD = ?, SEXO = ?, TELEFONO = ?, CELULAR = ? WHERE CEDULA = ?");
            ps.setString(1, this.ccTxt.getText());
            ps.setString(2, this.nameTxt.getText());
            ps.setString(3, this.lastTxt.getText());
            ps.setString(4, this.ageTxt.getText());
            ps.setString(5, this.gender.getSelectedItem().toString());
            ps.setString(6, this.phoneTxt.getText());
            ps.setString(7, this.mobileTxt.getText());
            ps.setString(8, this.ccTxt.getText());
            
            int res = ps.executeUpdate();
            
            if (res > 0) {
                JOptionPane.showMessageDialog(null, "Informacion actualizada");
            } else {
                JOptionPane.showMessageDialog(null, "Error: No se pudo actualizar");
            }
            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_modificarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        com.mysql.jdbc.Connection con = null;
        try {
            con = conect.getConection();

            ps = con.prepareStatement("DELETE FROM empleado WHERE CEDULA = ?");
            ps.setInt(1, Integer.parseInt(this.ccTxt.getText()));
            
            int res = ps.executeUpdate();
            if (res > 0) {
                JOptionPane.showMessageDialog(null, "Informacion Eliminada");
            } else {
                JOptionPane.showMessageDialog(null, "Error: No se pudo eliminar");
            }
            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_eliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageTxt;
    private javax.swing.JLabel borrarLbl;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField ccTxt;
    private javax.swing.JButton eliminar;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JButton ingresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastTxt;
    private javax.swing.JTextField mobileTxt;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTextField phoneTxt;
    // End of variables declaration//GEN-END:variables
}
